---
title: "GCM+LOCO"
author: "Chenghui Zheng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(MASS)
library(GeneralisedCovarianceMeasure)
```

####################GCM Simulation###################################
$$
a) Z \sim N(0,1), X = 2*sin(Z) + 0.1*N(0,1), Y = 2*sin(Z) + 0.1*N(0,1)
$$



```{r}
# Simulation for X is conditional independent of Y given Z
# Z is non-linear
simulate <- function(sample_sizes, num_simulations = 100, alpha = 0.05) {
  results <- data.frame(Sample_Size = numeric(0),
      Rejection_Rate = numeric(0))
  
  for (n in sample_sizes) {
    rejections <- 0
    
    for (i in 1:num_simulations) {
      Z <- rnorm(n)
      X <-2*sin(Z) +  0.1*rnorm(n)
      Y <-  2*sin(Z) +  0.1*rnorm(n)
      gcm_results <- gcm.test(X, Y, Z, regr.method = "kernel.ridge")
      p.value <- gcm_results$p.value
      
      if (p.value < alpha) {
        rejections <- rejections + 1
      }
    }
    
    type1_error <- rejections / num_simulations 

    
    results <- rbind(results, data.frame(
      Sample_Size = n,
      Rejection_Rate = type1_error
    ))
  }
  
  return(results)
}


sample_sizes <- c(50, 100, 200, 300, 500)
# Get duration of code execution
start <- proc.time()
set.seed(101)  
results1 <- simulate(sample_sizes)
print( proc.time() - start ) 
#   user  system elapsed 
#  5524.68  284.83 5885.64
#print(results)


write.csv(results1, "simulation_gcm1.csv", row.names = FALSE)


#pdf(file = "simulation_plot1.pdf")

ggplot(results_gcm1, aes(x = Sample_Size, y = Rejection_Rate)) +
  geom_line() +
  geom_point() +
  labs(title = "Rejection Rate vs. Sample Size",
       x = "Sample Size",
       y = "Rejection Rate") +
  theme_minimal()

#dev.off()
```

$$
b) Z \sim N(0,1), X = 2*Z + 0.1*N(0,1), Y = 2*Z + 0.1*N(0,1)
$$

```{r}
# Simulation for X is conditional independent of Y given Z
# Z is linear
simulate <- function(sample_sizes, num_simulations = 100, alpha = 0.05) {
  results <- data.frame(Sample_Size = numeric(0),
      Rejection_Rate = numeric(0))
  
  for (n in sample_sizes) {
    rejections <- 0
    
    for (i in 1:num_simulations) {
      Z <- rnorm(n)
      X <-2*Z +  0.1*rnorm(n)
      Y <-  2*Z +  0.1*rnorm(n)
      gcm_results <- gcm.test(X, Y, Z, regr.method = "kernel.ridge")
      p.value <- gcm_results$p.value
      
      if (p.value < alpha) {
        rejections <- rejections + 1
      }
    }
    
    type1_error <- rejections / num_simulations 

    
    results <- rbind(results, data.frame(
      Sample_Size = n,
      Rejection_Rate = type1_error
    ))
  }
  
  return(results)
}


sample_sizes <- c(50, 100, 200, 300, 500)
# Get duration of code execution
start <- proc.time()
set.seed(123)  
results_gcm2 <- simulate(sample_sizes)
print( proc.time() - start )
#print(results)
#    user  system elapsed 
#  7771.22  342.86 8270.81


write.csv(results_gcm2, "simulation_gcm2.csv", row.names = FALSE)

#pdf(file = "simulation_plot1.pdf")

ggplot(results_gcm2, aes(x = Sample_Size, y = Rejection_Rate)) +
  geom_line() +
  geom_point() +
  labs(title = "Rejection Rate vs. Sample Size",
       x = "Sample Size",
       y = "Rejection Rate") +
  theme_minimal()

#dev.off()
```


######################################GCM Filter Simulation########################
```{r}
library(MASS)
library(dplyr)
library(mvtnorm)
library(matrixcalc)
library(mlr)
library(iml)
library(ggplot2)
library(randomForest)
library(kknn)
source("stored_functions_for_GCM_LOCO.R")
```



```{r}
# case a) simulation with sample size 1000, 100 simulations
# each simulation takes roughly 22 sec
results <- data.frame(
  Averaged_Test_Statistic = numeric(0),
  Rejection_Rate = numeric(0)
)

num_simulation <- 100

# Initialize aggregate statistics and rejection count
aggregate_test_stat <- numeric(4)
rejections <- numeric(4) # Assuming 4 feature inputs
set.seed(101)
# Run simulations
for (i in 1:num_simulation) {
  # Specify entries for covariance matrix, pho=0
  sigma_indep <- diag(1, nrow = 4)
  data_indep <- as.data.frame(mvrnorm(n = 1000, 
                                      mu = rep(0, times = 4), 
                                      Sigma = sigma_indep))
  colnames(data_indep) <- c("X1", "X2", "X3", "X4")
  
  # Define response y
  y1 <- data_indep$X1 + data_indep$X2 + data_indep$X3 + rnorm(n = 1000, mean = 0, sd = 0.01)
  data_indep["y"] <- y1
  filter_results <- GCM_filter(data_indep, "regr.randomForest","y")

  # Aggregate test statistics and rejections
  aggregate_test_stat <- aggregate_test_stat + filter_results$resultGCM$test.statistics
  rejections <- rejections + filter_results$resultGCM$rejection
}


type1_error <- rejections / num_simulation
results <- rbind(results, data.frame(
  Averaged_Test_Statistic = aggregate_test_stat / num_simulation, 
  Rejection_Rate = type1_error
))

results$p_value <-as.numeric(2 * (1 - pnorm(abs(results$Averaged_Test_Statistic)))) 
```

```{r}

write.csv(results, "simulation_gcm_loco1.csv", row.names = FALSE)
```


```{r}
# case b) simulation with sample size 1000, 100 simulations
# each simulation takes roughly 22 sec
    results <- data.frame(Sample_Size = numeric(0),
    Rejection_Rate = numeric(0),averaged_test_statistic = numeric(0))
    num_simulation = 100
  
    aggregate_test_stat <- numeric(4)
    rejections <- numeric(4) # There are 4 feature input
    set.seed(101)
    for (i in 1:num_simulation) {
     # specify entries for covariance matrix, pho=0
        sigma_indep <- diag(1, nrow = 4)

        data_indep <- as.data.frame(rmvnorm(n = 1000, 
                                  mean = rep(0, times = 4), 
                                  sigma = sigma_indep))
        colnames(data_indep) <- c("X1", "X2", "X3", "X4")
        # Define response y2: 
        y2  <- data_indep$X1 + data_indep$X2 + (data_indep$X3)*0.001 + rnorm(n = 1000, mean = 0, sd = 0.01) 
 
        data_indep["y"]  <- y2

        filter_results <- GCM_filter(data_indep, "regr.randomForest", "y")
        aggregate_test_stat <- aggregate_test_stat + filter_results$resultGCM$test.statistics
        rejections <- rejections + filter_results$resultGCM$rejection
    }
    
    type1_error <- rejections / num_simulation 

    
    results2 <- rbind(results, data.frame(
      #Sample_Size = sample_sizes,
      Averaged_Test_Statistic =aggregate_test_stat/num_simulation, 
      Rejection_Rate = type1_error
    ))
  
  
results2$p_value <-as.numeric(2 * (1 -pnorm(abs(results2$Averaged_Test_Statistic)))) 

```


```{r}

write.csv(results2, "simulation_gcm_loco2.csv", row.names = FALSE)
```


```{r}
# case c), unconditional independent & different correlations
results3 <- data.frame(
  Correlation = numeric(0),
  Sample_Size = numeric(0),
  Averaged_Test_Statistic = numeric(0),
  Rejection_Rate = numeric(0)
)

# Simulation parameters
num_simulation <- 50
sample_size <- 1000
correlations <- c(0.01, 0.5, 0.75,0.99)
set.seed(101)
for (rho in correlations) {
  aggregate_test_stat <- numeric(4)
  rejections <- numeric(4)
  
  for (i in 1:num_simulation) {
    # Specify covariance matrix
    sigma <- diag(1, nrow = 4)
    sigma[1, 2] <- rho
    sigma[2, 1] <- rho
    
    # Generate correlated data
    data <- as.data.frame(mvrnorm(n = sample_size, 
                                  mu = rep(0, times = 4), 
                                  Sigma = sigma))
    colnames(data) <- c("X1", "X2", "X3", "X4")
    
    # Define response y
    y <- data$X1 + data$X2 + data$X3 + rnorm(n = sample_size, mean = 0, sd = 0.01)
    data["y"] <- y
    
    # Apply GCM_filter
    filter_results <- GCM_filter(data, "regr.randomForest", "y")
    
    # Aggregate test statistics and rejections
    aggregate_test_stat <- aggregate_test_stat + filter_results$resultGCM$test.statistics
    rejections <- rejections + filter_results$resultGCM$rejection
  }
  
  # Calculate type I error rate
  type1_error <- rejections / num_simulation
  
  # Append results to the results data frame
  results3 <- rbind(results3, data.frame(
    Correlation = rho,
    Sample_Size = sample_size,
    Averaged_Test_Statistic = aggregate_test_stat / num_simulation,
    Rejection_Rate = type1_error
  ))
}

results3$p_value <-as.numeric(2 * (1 - pnorm(abs(results3$Averaged_Test_Statistic)))) 
```

```{r}
write.csv(results3, "simulation_gcm_loco3.csv", row.names = FALSE)
```


```{r}
# case d), unconditional independent & different correlations
results4 <- data.frame(
  Correlation = numeric(0),
  Sample_Size = numeric(0),
  Averaged_Test_Statistic = numeric(0),
  Rejection_Rate = numeric(0)
)

num_simulation <- 50
sample_size <- 1000
correlations <- c(0.01, 0.5, 0.75,0.99)
set.seed(101)
for (rho in correlations) {
  aggregate_test_stat <- numeric(4)
  rejections <- numeric(4)
  
  for (i in 1:num_simulation) {
    # Specify covariance matrix
    sigma <- diag(1, nrow = 4)
    sigma[1, 2] <- rho
    sigma[2, 1] <- rho
    
    data <- as.data.frame(mvrnorm(n = sample_size, 
                                  mu = rep(0, times = 4), 
                                  Sigma = sigma))
    colnames(data) <- c("X1", "X2", "X3", "X4")
    
    # Define response y
    y <- data$X1 + data$X3 + rnorm(n = sample_size, mean = 0, sd = 0.01)
    data["y"] <- y
    
    filter_results <- GCM_filter(data, "regr.randomForest", "y")
    
    aggregate_test_stat <- aggregate_test_stat + filter_results$resultGCM$test.statistics
    rejections <- rejections + filter_results$resultGCM$rejection
  }
  
  type1_error <- rejections / num_simulation
  
  # Append results to the results data frame
  results4 <- rbind(results4, data.frame(
    Correlation = rho,
    Sample_Size = sample_size,
    Averaged_Test_Statistic = aggregate_test_stat / num_simulation,
    Rejection_Rate = type1_error
  ))
}

results4$p_value <-as.numeric(2 * (1 - pnorm(abs(results4$Averaged_Test_Statistic)))) 
```

```{r}
write.csv(results4, "simulation_gcm_loco4.csv", row.names = FALSE)
```


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%LOCO Simulation%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```{r}
# case a)
run_simulation_a <- function(num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 3*data_indep$X3 + 6*data_indep$X4+
          9 * data_indep$X5 + 10 * data_indep$X6 + 
          11 * data_indep$X7 + 15 * data_indep$X8  + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    # Run LOCO
    LOCO_results <- LOCO(data_indep, "regr.randomForest", "y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  
  return(aggregate_results(results_list))
}

start <- proc.time()
results_a <- run_simulation_a(10)
#selected_columns <- df[df$p_value < 0.05, ]
print( proc.time() - start )


write.csv(results_a, "simulation_loco1cplx.csv", row.names = FALSE)

#   user  system elapsed 
# 735.38   15.77  751.61

```


```{r}
# case b)

run_simulation_b <- function(cor, num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    sigma_indep[1, 2] <- cor
    sigma_indep[2, 1] <- cor
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <-  1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    # Run LOCO
    LOCO_results <- LOCO(data_indep, "regr.randomForest", "y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  return(aggregate_results(results_list))
}



start <- proc.time()
results2 <- data.frame()

correlations <- c(0, 0.5, 0.75, 0.9)


for (rho in correlations) {
  results_b <- run_simulation_b(cor = rho, num_simulations=10)
  
  results_b$Correlation <- rho
  
  results2 <- rbind(results2, results_b)
}
print( proc.time() - start )
write.csv(results2, "simulation_loco2.csv", row.names = FALSE)
#          user  system elapsed 
# 5808.50  122.69 5996.14  
```



```{r}
# case c)
run_simulation_c <- function(snr, num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- cplx_cov_matrix(n=20, rho=0.7)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <-  1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = snr)
    data_indep["y"] <- y1
    
    # Run LOCO
    LOCO_results <- LOCO(data_indep, "regr.randomForest", "y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  return(aggregate_results(results_list))
}



start <- proc.time()
results3 <- data.frame()

snrs <- c(0.1, 0.5, 0.75, 2.1)


for (sigma in snrs) {
  results_c <- run_simulation_c(snr = sigma, num_simulations=10)
  
  results_c$snr <- sigma
  
  results3 <- rbind(results3, results_c)
}
print( proc.time() - start )
write.csv(results3, "simulation_loco3.csv", row.names = FALSE)
#       user  system elapsed 
# 5078.91  110.02 5221.17 
```



```{r}
# case d) non-linear
run_simulation_d <- function(num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 2*(data_indep$X1)^2 + 2*cos(4*data_indep$X2) + sin(data_indep$X3) + exp(data_indep$X4/3)+ 3*data_indep$X5 * data_indep$X6 + 
          5 * data_indep$X7 + pmax(data_indep$X8)  + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    # Run LOCO
    LOCO_results <- LOCO(data_indep, "regr.randomForest", "y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  
  return(aggregate_results(results_list))
}

start <- proc.time()
results_d <- run_simulation_d(10)
print( proc.time() - start )


write.csv(results_d, "simulation_loco4.csv", row.names = FALSE)
#   user  system elapsed 
#1382.86   25.92 1437.05
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%GCM Filter Only%%%%%%%%%%%%%%%%%%%%%%%%%
```{r}
# case a)
run_simulation_a <- function(num_simulations, Alpha = 0.05) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    GCM_results <- GCM_filter(data_indep, "regr.randomForest", "y", alpha = Alpha)[[1]]
    
    # Store the results in the list
    results_list[[i]] <- GCM_results
  }
  
  return(aggregate_results(results_list))
}

start <- proc.time()
results_a <- run_simulation_a(10, Alpha = 0.05)
#selected_columns <- df[df$p_value < 0.05, ]
print( proc.time() - start )


write.csv(results_a, "simulation_gcm_filter1.csv", row.names = FALSE)

#    user  system elapsed 
# 841.43   15.22  864.69 


#   user  system elapsed 
# 843.30   15.75  868.33 
```


```{r}
# case b)

run_simulation_b <- function(cor, num_simulations, Alpha = 0.05) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    sigma_indep[1, 2] <- cor
    sigma_indep[2, 1] <- cor
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    # Run LOCO
    GCM_results <- GCM_filter(data_indep, "regr.randomForest", "y",alpha = Alpha)[[1]]
    
    # Store the results in the list
    results_list[[i]] <- GCM_results
  }
  return(aggregate_results(results_list))
}



start <- proc.time()
results2 <- data.frame()

correlations <- c(0, 0.5, 0.75, 0.9)


for (rho in correlations) {
  results_b <- run_simulation_b(cor = rho, num_simulations=10, Alpha = 0.01)
  
  results_b$Correlation <- rho
  
  results2 <- rbind(results2, results_b)
}
print( proc.time() - start )
write.csv(results2, "simulation_0.01gcm_filter2.csv", row.names = FALSE)
#      user  system elapsed 
# 3670.77   60.44 3749.76 

#user  system elapsed 
#3210.19   57.01 3284.72 
```


```{r}
# case c)
run_simulation_c <- function(snr, num_simulations, Alpha = 0.05) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- cplx_cov_matrix(n=20, rho=0.7)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = snr)
    data_indep["y"] <- y1
    
    # Run LOCO
    GCM_results <- GCM_filter(data_indep, "regr.randomForest", "y", alpha = Alpha)[[1]]
    
    # Store the results in the list
    results_list[[i]] <- GCM_results
  }
  return(aggregate_results(results_list))
}



start <- proc.time()
results3 <- data.frame()

snrs <- c(0.1, 0.5, 0.75, 2.1)


for (sigma in snrs) {
  results_c <- run_simulation_c(snr = sigma, num_simulations=10,Alpha=0.01)
  
  results_c$snr <- sigma
  
  results3 <- rbind(results3, results_c)
}
print( proc.time() - start )
write.csv(results3, "simulation_0.01gcm_filter3.csv", row.names = FALSE)
#       user  system elapsed 
#3670.77   60.44 3749.76 

# user  system elapsed 
#2801.21   57.23 2919.05 
```


```{r}
# case d) non-linear
run_simulation_d <- function(num_simulations, Alpha = 0.05) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 2*(data_indep$X1)^2 + 2*cos(4*data_indep$X2) + sin(data_indep$X3) + exp(data_indep$X4/3)+ 3*data_indep$X5 * data_indep$X6 + 
          5 * data_indep$X7 + pmax(data_indep$X8)  + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    # Run LOCO
    GCM_results <- GCM_filter(data_indep, "regr.randomForest", "y", alpha = Alpha)[[1]]
    
    # Store the results in the list
    results_list[[i]] <- GCM_results
  }
  
  return(aggregate_results(results_list))
}

start <- proc.time()
results_d <- run_simulation_d(10, Alpha = 0.01)
print( proc.time() - start )


write.csv(results_d, "simulation0.01_gcm_filter4.csv", row.names = FALSE)
# user  system elapsed 
# 924.77   14.90  951.89

 #user  system elapsed 
 #937.92   14.78  958.58 
```


%%%%%%%%%%%%%%%%%%%%%%GCM Filter First + LOCO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```{r}
library(tidyverse)
library(dplyr)
# case a)
run_simulation_a <- function(num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    filter_results <- GCM_filter(data_indep, "regr.randomForest","y")[[2]]
    LOCO_results <-LOCO(filter_results, "regr.randomForest","y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  
  return(aggregate_results(results_list))
}

start <- proc.time()
results_a <- run_simulation_a(10)
print( proc.time() - start )

write.csv(results_a, "simulation_alg1.csv", row.names = FALSE)
#    user  system elapsed 
#1159.51   29.23 1209.42 
```

```{r}
# case b)

run_simulation_b <- function(cor, num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    sigma_indep[1, 2] <- cor
    sigma_indep[2, 1] <- cor
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    filter_results <- GCM_filter(data_indep, "regr.randomForest","y")[[2]]
    LOCO_results <-LOCO(filter_results, "regr.randomForest","y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  return(aggregate_results(results_list))
}



start <- proc.time()
results2 <- data.frame()

correlations <- c(0, 0.5, 0.75, 0.9)


for (rho in correlations) {
  results_b <- run_simulation_b(cor = rho, num_simulations=10)
  
  results_b$Correlation <- rho
  
  results2 <- rbind(results2, results_b)
}

print( proc.time() - start )
#write.csv(results2, "simulation_alg2.csv", row.names = FALSE)
#   user  system elapsed 
# 5815.61  147.71 6110.84 
```


```{r}
# case c)
run_simulation_c <- function(snr, num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- cplx_cov_matrix(n=20, rho=0.7)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 1.5*data_indep$X1 + 1.5*data_indep$X2 + 2*data_indep$X3 + 2*data_indep$X4+
          2 * data_indep$X5 + 3 * data_indep$X6 + 
          4 * data_indep$X7 + 5 * data_indep$X8 + 
          rnorm(n = 500, mean = 0, sd = snr)
    data_indep["y"] <- y1
    
    filter_results <- GCM_filter(data_indep, "regr.randomForest","y")[[2]]
    LOCO_results <-LOCO(filter_results, "regr.randomForest","y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  return(aggregate_results(results_list))
}



start <- proc.time()
results3 <- data.frame()

snrs <- c(0.1, 0.5, 0.75, 2.1)


for (sigma in snrs) {
  results_c <- run_simulation_c(snr = sigma, num_simulations=10)
  
  results_c$snr <- sigma
  
  results3 <- rbind(results3, results_c)
}
print( proc.time() - start )
write.csv(results3, "simulation_alg3.csv", row.names = FALSE)
#   user  system elapsed 
#5704.52  155.75 5957.70  
```


```{r}
# case d) non-linear
run_simulation_d <- function(num_simulations) {
  results_list <- list()
  
  for (i in 1:num_simulations) {
    set.seed(123 + i)  
    
    sigma_indep <- diag(1, nrow = 20)
    data_indep <- as.data.frame(mvrnorm(n = 500, 
                                        mu = rep(0, times = 20), 
                                        Sigma = sigma_indep))
    colnames(data_indep) <- paste("X", 1:20, sep = "")
    
    # Define response y
    y1 <- 2*(data_indep$X1)^2 + 2*cos(4*data_indep$X2) + sin(data_indep$X3) + exp(data_indep$X4/3)+ 3*data_indep$X5 * data_indep$X6 + 
          5 * data_indep$X7 + pmax(data_indep$X8)  + 
          rnorm(n = 500, mean = 0, sd = 0.1)
    data_indep["y"] <- y1
    
    filter_results <- GCM_filter(data_indep, "regr.randomForest","y")[[2]]
    filter_results["y"] <- y1
    LOCO_results <-LOCO(filter_results, "regr.randomForest","y")
    
    # Store the results in the list
    results_list[[i]] <- LOCO_results
  }
  
  return(aggregate_results(results_list))
}

start <- proc.time()
results_d <- run_simulation_d(10)
print( proc.time() - start )


#write.csv(results_d, "simulation_alg4.csv", row.names = FALSE)
#     user  system elapsed 
#1530.30   32.86 1588.26 
```